### ISSUE TITLE
Issue with run_ZOGY

### ISSUE THREAD

**Issue by fulsdavid** [GOTO-OBS/ZiP#4]
Thank you for putting this together. I have ran into a few issues, but have been working to resolve them. 
I noticed that there were a few bugs in the zip.py routine, line 706:
     finp(SLICE, outname, xslice, yslice, clean_sci, clean_ref, blckout)
I think the last variable should be "blackout".
line 703:
     imprep(sci_im, ref_im, name, sub_imagex, sub_imagey, lineup = align)
I think the variable "name" is not needed.

After making these changes, I can get the two test images 1.fits and 2.fits to run nicely, but I am having trouble getting my .fits files through the process. I get this error:

/usr/local/lib/python3.6/dist-packages/zogyp/configfls
Serial version
WARNING: FITSFixedWarning: 'datfix' made the change 'Changed '' to '2018-03-16''. [astropy.wcs.wcs]
Making PSF catalog
Making PSF catalog
Modelling PSF for ./Zoutput/ref_cut1.fits
Modelling PSF for ./Zoutput/sci_cut1.fits
/usr/local/lib/python3.6/dist-packages/numpy-1.16.3-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy-1.16.3-py3.6-linux-x86_64.egg/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    run_ZOGY(T[0], T[1], xslice=5, yslice=5, blackout=True, outname='TEST_SUB') #ZOGY image subtraction T[0] - T[1]
  File "/usr/local/lib/python3.6/dist-packages/zogyp/zip.py", line 708, in run_ZOGY
    finp(SLICE, outname, xslice, yslice, clean_sci, clean_ref, blackout)
  File "/usr/local/lib/python3.6/dist-packages/zogyp/zip.py", line 622, in finp
    cdat, psf = chop_kern(sub_dat, psf_dat, psf_hed, xslice, yslice, clean_sci)
  File "/usr/local/lib/python3.6/dist-packages/zogyp/zip.py", line 264, in chop_kern
    sub_img[i].shape[0], cents[i][1], cents[i][0], slices, i))
  File "/usr/local/lib/python3.6/dist-packages/zogyp/zip.py", line 164, in psf_map
    polzero1 = header['POLZERO1']
  File "/usr/local/lib/python3.6/dist-packages/astropy-3.1.2-py3.6-linux-x86_64.egg/astropy/io/fits/header.py", line 145, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/usr/local/lib/python3.6/dist-packages/astropy-3.1.2-py3.6-linux-x86_64.egg/astropy/io/fits/header.py", line 1654, in _cardindex
    raise KeyError("Keyword {!r} not found.".format(keyword))
KeyError: "Keyword 'POLZERO1' not found."

Any ideas on what could be wrong with my images? I've included the text of my two image headers.
[ref_head.txt](https://github.com/GOTO-OBS/ZiP/files/3114952/ref_head.txt)
[sci_head.txt](https://github.com/GOTO-OBS/ZiP/files/3114953/sci_head.txt)

**Comment by ryanc123** [comment]
Hi fulsdavid,

Firstly, apologies for the delayed response. 
Thanks for the comments, I completely missed the errors for the serial branch! 
Good news, it's not your input headers. POLZERO1 is a PSFex key word introduced after the PSF has been sampled. Chances are, you're under sampling  your input images. Which means 1 of 2 issues here:

1.) Your SEXtractor params are too strict for the image. You can make changes to this ./zogyp/configfls/default.sex (just a regular text file) and changing DETECT_MINAREA, DETECT_THRESH, and, ANALYSIS_THRESH to lower values. 

2.) Your field of view is too small to correctly map the PSF. 

It's most likely 1 as the default sextractor params are quite strict.
Let me know if that helps.

**Comment by ryanc123** [comment]
I'm going to close this issue for now, but feel free to reopen it if your problem persists

**Comment by fulsdavid** [comment]
I'm still not getting my images through the pipeline, and for the same reason. However, the test images included with the package go through, so I am guessing the fault lies with my images and not the code specifically. I've tried playing around with the sextractor settings, and when I run with ASCII output, get plenty of sources (8000-13000 depending on the sextractor settings), but still no POLZERO1 values in the output . My field is extremely large (19.8 sq deg.) so maybe that is the issue? I will keep investigating.

**Comment by ryanc123** [comment]
That is peculiar, have you tried using the sub_imagex = 1, sub_imagey =1 parameters. 
It slices the image into smaller chunks for PSF modelling and background subtraction. 

If you're okay sharing the data, I'd be happy to see if I can fix it my end.
